### ISSUE TITLE
TextMate/Sublime theme and TmTheme Editor

### ISSUE THREAD

**Issue by Poorchop** [Poorchop/darktooth-theme-ports#3]
@jasonm23 I used the [TmTheme Editor](https://tmtheme-editor.herokuapp.com) again for the sake of generating a possible Sublime theme, but I figured that I'd do the common sense thing this time and have you take a look at it. It's online and easy to share with plenty of code previews available, so you can easily tweak it and hopefully share your changes with me. This might help with the gray area issues that I've been having with some editors. I might even go back and change a few themes like the Brackets one.

I used Monokai as a starting template but it might be a better idea to used Solarized or another theme with more default syntax categories. All of the italics, underlined, and bold options are leftovers from the default Monokai theme that loads up. Here's what I have so far:

![screen shot 2016-05-11 at 21 18 07](https://cloud.githubusercontent.com/assets/5256208/15201430/e4980cfe-17be-11e6-9323-c50911c40356.png)

Everything looks good except for C# and Python, which look awful. The site generates a .tmTheme file that I can share with you via your preferred method in case you want to play around with it on your end.

**Comment by jasonm23** [comment]
Looks pretty good.

**Comment by jasonm23** [comment]
XML/HTML?

**Comment by Poorchop** [comment]
HTML left, Python right - no XML preview built into the theme editor. The HTML looks sort of bland, especially compared to the other ports that I've done. I believe that your original emacs theme only specifies colors for the tag name itself and delimiter, nothing about attributes.

On second thought, I just need to set up emacs on this computer and load the code examples there to see what everything is supposed to look like by default. It'll save you some headache.

![untitled](https://cloud.githubusercontent.com/assets/5256208/15205105/80c7c8b2-17e2-11e6-9499-907d004f4d28.png)

**Comment by jasonm23** [comment]
> Install Emacs (ed: and Darktooth)

Yes that will really help.  As long as you achieve consistency with the Emacs version, I'll have no complaints.

**Comment by Poorchop** [comment]
I published this to the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Poorchop.theme-darktooth). I think most languages look excellent except for JavaScript at the moment. I'd like to go back and modify the Brackets theme for consistency when I'm feeling more motivated.

Hopefully more people will jump on board and help with the other ports, especially unfinished ones like Atom, which is an especially annoying editor in my experience.

**Comment by jasonm23** [comment]
Note that JS2 is the mode I designed the javascript support against, so do your Emacs comparisons with that mode enabled.

I am looking at a fair bit of JSX and no doubt more in future, so that will get some love if there are faces available for the \*ml nodes.
